export const BOTAO_CLICADO_SUCESS = "BOTAO_CLICADO_SUCESS"
export const BOTAO_CLICADO_REQUEST = "BOTAO_CLICADO_REQUEST"
export const BOTAO_CLICADO_FAILURE = "BOTAO_CLICADO_FAILURE"

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const PERSIST_REHYDRATE = 'persist/REHYDRATE'

export const REEGISTER_REQUEST = 'REEGISTER_REQUEST'
export const REEGISTER_SUCESS = 'REEGISTER_SUCESS'
export const REEGISTER_FAILUREE = 'REEGISTER_FAILUREE'
export const REGISTER_UPDATED_SUCESS = 'REGISTER_UPDATED_SUCESS'
export const REGISTER_CREATED_SUCESS = 'REGISTER_CREATED_SUCESS'
